// Tablo tanımları — SQLite (yerel) ve PostgreSQL (Vercel/Neon) için ortak.
export const SCHEMA_VERSION = 2;

const TYPES = {
  sqlite: { id: 'INTEGER PRIMARY KEY AUTOINCREMENT', real: 'REAL' },
  pg: { id: 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', real: 'DOUBLE PRECISION' },
};

export function schemaStatements(dialect) {
  const { id, real } = TYPES[dialect];
  return [
    `CREATE TABLE IF NOT EXISTS items (
      id ${id},
      sku TEXT UNIQUE,
      name TEXT NOT NULL,
      kind TEXT NOT NULL DEFAULT 'parca',
      category TEXT NOT NULL DEFAULT '',
      brand TEXT NOT NULL DEFAULT '',
      model TEXT NOT NULL DEFAULT '',
      compatible TEXT NOT NULL DEFAULT '',
      serial TEXT NOT NULL DEFAULT '',
      condition TEXT NOT NULL DEFAULT 'yeni',
      status TEXT NOT NULL DEFAULT 'stokta',
      quantity ${real} NOT NULL DEFAULT 0,
      unit TEXT NOT NULL DEFAULT 'adet',
      min_quantity ${real} NOT NULL DEFAULT 0,
      location TEXT NOT NULL DEFAULT '',
      purchase_price ${real} NOT NULL DEFAULT 0,
      sale_price ${real} NOT NULL DEFAULT 0,
      source TEXT NOT NULL DEFAULT '',
      parent_id INTEGER REFERENCES items(id) ON DELETE SET NULL,
      photo TEXT NOT NULL DEFAULT '',
      notes TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS movements (
      id ${id},
      item_id INTEGER REFERENCES items(id) ON DELETE SET NULL,
      item_name TEXT NOT NULL DEFAULT '',
      item_sku TEXT NOT NULL DEFAULT '',
      kind TEXT NOT NULL,
      qty ${real} NOT NULL,
      unit_price ${real} NOT NULL DEFAULT 0,
      unit_cost ${real} NOT NULL DEFAULT 0,
      note TEXT NOT NULL DEFAULT '',
      repair_id INTEGER,
      created_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS repairs (
      id ${id},
      code TEXT UNIQUE,
      customer TEXT NOT NULL DEFAULT '',
      phone TEXT NOT NULL DEFAULT '',
      device TEXT NOT NULL DEFAULT '',
      serial TEXT NOT NULL DEFAULT '',
      problem TEXT NOT NULL DEFAULT '',
      diagnosis TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'bekliyor',
      fee ${real} NOT NULL DEFAULT 0,
      deposit ${real} NOT NULL DEFAULT 0,
      paid INTEGER NOT NULL DEFAULT 0,
      notes TEXT NOT NULL DEFAULT '',
      received_at TEXT NOT NULL DEFAULT '',
      delivered_at TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS repair_parts (
      id ${id},
      repair_id INTEGER NOT NULL REFERENCES repairs(id) ON DELETE CASCADE,
      item_id INTEGER REFERENCES items(id) ON DELETE SET NULL,
      item_name TEXT NOT NULL DEFAULT '',
      qty ${real} NOT NULL,
      unit_cost ${real} NOT NULL DEFAULT 0,
      unit_price ${real} NOT NULL DEFAULT 0,
      movement_id INTEGER
    )`,
    `CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS auth_fails (
      ip TEXT PRIMARY KEY,
      count INTEGER NOT NULL DEFAULT 0,
      until TEXT NOT NULL DEFAULT ''
    )`,
    'CREATE INDEX IF NOT EXISTS idx_mov_item ON movements(item_id)',
    'CREATE INDEX IF NOT EXISTS idx_mov_date ON movements(created_at)',
    'CREATE INDEX IF NOT EXISTS idx_items_parent ON items(parent_id)',
    'CREATE INDEX IF NOT EXISTS idx_rp_repair ON repair_parts(repair_id)',
  ];
}

// Yedekten geri yüklemede kabul edilen sütunlar
export const COLUMNS = {
  items: ['id', 'sku', 'name', 'kind', 'category', 'brand', 'model', 'compatible', 'serial', 'condition', 'status',
    'quantity', 'unit', 'min_quantity', 'location', 'purchase_price', 'sale_price', 'source', 'parent_id', 'photo',
    'notes', 'created_at', 'updated_at'],
  movements: ['id', 'item_id', 'item_name', 'item_sku', 'kind', 'qty', 'unit_price', 'unit_cost', 'note', 'repair_id', 'created_at'],
  repairs: ['id', 'code', 'customer', 'phone', 'device', 'serial', 'problem', 'diagnosis', 'status', 'fee', 'deposit',
    'paid', 'notes', 'received_at', 'delivered_at', 'created_at', 'updated_at'],
  repair_parts: ['id', 'repair_id', 'item_id', 'item_name', 'qty', 'unit_cost', 'unit_price', 'movement_id'],
  settings: ['key', 'value'],
};
